import type { Metadata } from 'next';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import './globals.css';
import MaterialProvider from '@/providers/MaterialProvider';
import NavBar from '@/components/NavBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className="h-full">
          <MaterialProvider>{children}</MaterialProvider>
        </body>
      </UserProvider>
    </html>
  );
}
