import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import MaterialProvider from "@/providers/MaterialProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
      <body className="h-full" >
      <MaterialProvider>
        <NavBar />
        {children}
      </MaterialProvider>
      </body>
      </UserProvider>
    </html>
  );
}
